<h1>try...catch</h1> <p>The <code>try...catch</code> statement marks a block of statements to try, and specifies a response, should an exception be thrown.</p> <iframe src="https://interactive-examples.mdn.mozilla.net/pages/js/statement-trycatch.html" frameborder="0" width="100%" class="interactive interactive-js" height="250"></iframe>  <h2 id="Syntax">Syntax</h2> <pre class="syntaxbox">try {
   <em>try_statements</em>
}
[catch (<em>exception_var_1</em> if <em>condition_1</em>) { // non-standard
   <em>catch_statements_1</em>
}]
...
[catch (<em>exception_var_2</em>) {
   <em>catch_statements_2</em>
}]
[finally {
   <em>finally_statements</em>
}]
</pre> <dl> <dt><code>try_statements</code></dt> <dd>The statements to be executed.</dd> </dl> <dl> <dt>
<code>catch_statements_1</code>, <code>catch_statements_2</code>
</dt> <dd>Statements that are executed if an exception is thrown in the <code>try</code> block.</dd> </dl> <dl> <dt>
<code>exception_var_1</code>, <code>exception_var_2</code>
</dt> <dd>An identifier to hold an exception object for the associated <code>catch</code> clause.</dd> </dl> <dl> <dt><code>condition_1</code></dt> <dd>A conditional expression.</dd> </dl> <dl> <dt><code>finally_statements</code></dt> <dd>Statements that are executed after the <code>try</code> statement completes. These statements execute regardless of whether an exception was thrown or caught.</dd> </dl> <h2 id="Description">Description</h2> <p>The <code>try</code> statement consists of a <code>try</code> block, which contains one or more statements. <code>{}</code> must always be used, also for single statements. At least one <code>catch</code> clause, or a <code>finally</code> clause, must be present. This gives us three forms for the <code>try</code> statement:</p> <ol> <li><code>try...catch</code></li> <li><code>try...finally</code></li> <li><code>try...catch...finally</code></li> </ol> <p>A <code>catch</code> clause contains statements that specify what to do if an exception is thrown in the <code>try</code> block. That is, you want the <code>try</code> block to succeed, and if it does not succeed, you want to pass control to the <code>catch</code> block. If any statement within the <code>try</code> block (or in a function called from within the <code>try</code> block) throws an exception, control is immediately shifted to the <code>catch</code> clause. If no exception is thrown in the <code>try</code> block, the <code>catch</code> clause is skipped.</p> <p>The <code>finally</code> clause executes after the <code>try</code> block and <code>catch</code> clause(s) execute but before the statements following the <code>try</code> statement. It always executes, regardless of whether an exception was thrown or caught.</p> <p>You can nest one or more <code>try</code> statements. If an inner <code>try</code> statement does not have a <code>catch</code> clause, the enclosing <code>try</code> statement's <code>catch</code> clause is entered.</p> <p>You can also use the <code>try</code> statement to handle JavaScript exceptions. See the <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide">JavaScript Guide</a> for more information on JavaScript exceptions.</p> <h3 id="Unconditional_catch_clause">Unconditional <code>catch</code> clause</h3> <p>When a single, unconditional <code>catch</code> clause is used, the <code>catch</code> block is entered when any exception is thrown. For example, when the exception occurs in the following code, control transfers to the <code>catch</code> clause.</p> <pre data-language="js">try {
   throw 'myException'; // generates an exception
}
catch (e) {
   // statements to handle any exceptions
   logMyErrors(e); // pass exception object to error handler
}
</pre> <p>The <code>catch</code> block specifies an identifier (<code>e</code> in the example above) that holds the value specified by the <code>throw</code> statement. The <code>catch</code> block is unique in that JavaScript creates this identifier when the <code>catch</code> block is entered and it adds it to the current scope; the identifier lasts only for the duration of the <code>catch</code> block; after the <code>catch</code> block finishes executing, the identifier is no longer available.</p> <h3 id="Conditional_catch_clauses">Conditional <code>catch</code> clauses</h3> <div class="blockIndicator nonStandard nonStandardHeader"> <p><strong> Non-standard</strong><br> This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user. There may also be large incompatibilities between implementations and the behavior may change in the future.</p> </div> <p>You can also use one or more conditional <code>catch</code> clauses to handle specific exceptions. In this case, the appropriate <code>catch</code> clause is entered when the specified exception is thrown. In the following example, code in the <code>try</code> block can potentially throw three exceptions: <a href="../global_objects/typeerror"><code>TypeError</code></a>, <a href="../global_objects/rangeerror"><code>RangeError</code></a>, and <a href="../global_objects/evalerror"><code>EvalError</code></a>. When an exception occurs, control transfers to the appropriate <code>catch</code> clause. If the exception is not one of the specified exceptions and an unconditional <code>catch</code> clause is found, control transfers to that <code>catch</code> clause.</p> <p>If you use an unconditional <code>catch</code> clause with one or more conditional <code>catch</code> clauses, the unconditional <code>catch</code> clause must be specified last. Otherwise, the unconditional <code>catch</code> clause will intercept all types of exception before they can reach the conditional ones.</p> <p>Reminder: this functionality is not part of the ECMAScript specification and has been removed in Firefox 59. It's not supported in any current browser anymore.</p> <pre data-language="js">try {
    myroutine(); // may throw three types of exceptions
} catch (e if e instanceof TypeError) {
    // statements to handle TypeError exceptions
} catch (e if e instanceof RangeError) {
    // statements to handle RangeError exceptions
} catch (e if e instanceof EvalError) {
    // statements to handle EvalError exceptions
} catch (e) {
    // statements to handle any unspecified exceptions
    logMyErrors(e); // pass exception object to error handler
}
</pre> <p>Here is the same "Conditional catch clauses" using code that conforms to ECMAScript specification (obviously it's verbose, but works everywhere):</p> <pre data-language="js">try {
    myroutine(); // may throw three types of exceptions
} catch (e) {
    if (e instanceof TypeError) {
        // statements to handle TypeError exceptions
    } else if (e instanceof RangeError) {
        // statements to handle RangeError exceptions
    } else if (e instanceof EvalError) {
        // statements to handle EvalError exceptions
    } else {
       // statements to handle any unspecified exceptions
       logMyErrors(e); // pass exception object to error handler
    }
}
</pre> <h3 id="The_exception_identifier">The exception identifier</h3> <p>When an exception is thrown in the <code>try</code> block, <em><code>exception_var</code></em> (e.g. the <code>e</code> in <code>catch (e)</code>) holds the value specified by the <code>throw</code> statement. You can use this identifier to get information about the exception that was thrown. This identifier is local to the <code>catch</code> clause. That is, it is created when the <code>catch</code> clause is entered, and after the <code>catch</code> clause finishes executing, the identifier is no longer available.</p> <div class="warning"> <p>In Firefox 58, when the exception is unused, the identifier can be omitted, as in the code below. This is also <a href="https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-5.html">allowed in TypeScript 2.5</a> and later. However, at the time of this writing (August 2018), <a href="https://github.com/tc39/proposal-optional-catch-binding">the proposal to support this</a> has not yet been included into an ECMAScript standard, so this syntax may not work in other browsers.</p> </div> <pre data-language="js">function isValidJSON(text) {
    try {
        JSON.parse(text);
        return true;
    } catch {
        return false;
    }
}
</pre>  <h3 id="The_finally_clause">The <code>finally</code> clause</h3> <p>The <code>finally</code> clause contains statements to execute after the <code>try</code> block and <code>catch</code> clause(s) execute, but before the statements following the <code>try..catch..finally</code> block. Note that the <code>finally</code> clause executes regardless of whether an exception is thrown. Also, if an exception is thrown, the statements in the <code>finally</code> clause execute even if no <code>catch</code> clause handles the exception. </p> <p>You can use the <code>finally</code> clause to make your script fail gracefully when an exception occurs; for example, to do general cleanup, you may need to release a resource that your script has tied up.</p> <p>It may seem strange to have a special exception-related clause that executes <strong>regardless</strong> of whether there is an exception, but this construct actually does serve a purpose. The important point is not that the <code>finally</code>-clause always executes, but rather that ordinary code following a <code>try..catch</code> does not. </p> <p>For instance, if another exception occurs inside a try's catch-block, any remaining code in the same outer try-block enclosing that try..catch (or in the main flow, if not in an outer try-block) , will not get executed, since control is immediately transferred to the outer try's catch-block (or the internal error-generator, if not in a try-block). </p> <p>Thus, any routine cleanup code done in that enclosed (or the main) section before it exits, will be skipped. However, If the try-block has a finally-block, then that finally-block code will be executed first to permit any such cleanup, and THEN the other try's catch-block (or the error-generator) will get control to handle the second exception. </p> <p>Now, if that routine cleanup must be done whether or not the try..catch code succeeds, then if the finally-block only executed after an exception, the same cleanup code would have to be duplicated both inside and outside the finally-block, and therefore there is no reason not to have just the finally-block alone, and let it execute regardless of exceptions or not.</p> <p>The following example opens a file and then executes statements that use the file (server-side JavaScript allows you to access files). If an exception is thrown while the file is open, the <code>finally</code> clause closes the file before the script fails. The code in <code>finally</code> also executes upon explicitly returning from <code>try</code> or <code>catch</code> block.</p> <pre data-language="js">openMyFile();
try {
   // tie up a resource
   writeMyFile(theData);
}
finally {
   closeMyFile(); // always close the resource
}
</pre> <h2 id="Examples">Examples</h2> <h3 id="Nested_try-blocks">Nested try-blocks</h3> <p>First, let's see what happens with this:</p> <pre data-language="js">try {
  try {
    throw new Error('oops');
  }
  finally {
    console.log('finally');
  }
}
catch (ex) {
  console.error('outer', ex.message);
}

// Output:
// "finally"
// "outer" "oops"
</pre> <p>Now, if we already caught the exception in the inner try-block by adding a catch block</p> <pre data-language="js">try {
  try {
    throw new Error('oops');
  }
  catch (ex) {
    console.error('inner', ex.message);
  }
  finally {
    console.log('finally');
  }
}
catch (ex) {
  console.error('outer', ex.message);
}

// Output:
// "inner" "oops"
// "finally"
</pre> <p>And now, let's re-throw the error.</p> <pre data-language="js">try {
  try {
    throw new Error('oops');
  }
  catch (ex) {
    console.error('inner', ex.message);
    throw ex;
  }
  finally {
    console.log('finally');
  }
}
catch (ex) {
  console.error('outer', ex.message);
}

// Output:
// "inner" "oops"
// "finally"
// "outer" "oops"
</pre> <p>Any given exception will be caught only once by the nearest enclosing catch-block unless it is re-thrown. Of course, any new exceptions raised in the "inner" block (because the code in catch-block may do something that throws), will be caught by the "outer" block.</p> <h3 id="Returning_from_a_finally_block">Returning from a finally block</h3> <p>If the <code>finally</code> block returns a value, this value becomes the return value of the entire <code>try-catch-finally</code> production, regardless of any <code>return</code> statements in the <code>try</code> and <code>catch</code> blocks. This includes exceptions thrown inside of the catch block:</p> <pre data-language="js">(function() {
  try {
    try {
      throw new Error('oops');
    }
    catch (ex) {
      console.error('inner', ex.message);
      throw ex;
    }
    finally {
      console.log('finally');
      return;
    }
  }
  catch (ex) {
    console.error('outer', ex.message);
  }
})();

// Output:
// "inner" "oops"
// "finally"</pre> <p>The outer "oops" is not thrown because of the return in the finally block. The same would apply to any value returned from the catch block.</p> <h2 id="Specifications">Specifications</h2> <div class="_table"><table class="standard-table"> <tbody> <tr> <th scope="col">Specification</th> <th scope="col">Status</th> <th scope="col">Comment</th> </tr> <tr> <td><a href="https://www.ecma-international.org/publications/files/ECMA-ST-ARCH/ECMA-262,%203rd%20edition,%20December%201999.pdf" hreflang="en">ECMAScript 3rd Edition (ECMA-262)</a></td> <td><span class="spec-Standard">Standard</span></td> <td>Initial definition. Implemented in JavaScript 1.4</td> </tr> <tr> <td><a href="https://www.ecma-international.org/ecma-262/5.1/#sec-12.14" hreflang="en">ECMAScript 5.1 (ECMA-262)<br><small>The definition of 'try statement' in that specification.</small></a></td> <td><span class="spec-Standard">Standard</span></td> <td> </td> </tr> <tr> <td><a href="https://www.ecma-international.org/ecma-262/6.0/#sec-try-statement" hreflang="en">ECMAScript 2015 (6th Edition, ECMA-262)<br><small>The definition of 'try statement' in that specification.</small></a></td> <td><span class="spec-Standard">Standard</span></td> <td> </td> </tr> <tr> <td><a href="https://tc39.github.io/ecma262/#sec-try-statement" hreflang="en">ECMAScript Latest Draft (ECMA-262)<br><small>The definition of 'try statement' in that specification.</small></a></td> <td><span class="spec-Draft">Draft</span></td> <td>Not part of the current ECMA-262 standard: Multiple catch clauses and conditional clauses (SpiderMonkey extension, JavaScript 1.5).</td> </tr> </tbody> </table></div> <h2 id="Browser_compatibility">Browser compatibility<a href="https://github.com/mdn/browser-compat-data" class="bc-github-link">Update compatibility data on GitHub</a>
</h2>  <div class="_table">
<table class="bc-table bc-table-js">
<thead>
<tr class="bc-platforms">
<th></th>
<th colspan="6">Desktop</th>
</tr>
<tr class="bc-browsers">
<th></th>
<th>Chrome</th>
<th>Edge</th>
<th>Firefox</th>
<th>Internet Explorer</th>
<th>Opera</th>
<th>Safari</th>
</tr>
</thead>
<tbody>
<tr>
<th scope="row">Basic support</th>
<td class="bc-supports-yes"> Yes</td>
<td class="bc-supports-yes"> Yes</td>
<td class="bc-supports-yes"> 1</td>
<td class="bc-supports-yes"> 6</td>
<td class="bc-supports-yes"> Yes</td>
<td class="bc-supports-yes"> Yes</td>
</tr>
<tr>
<th scope="row">Conditional clauses 
</th>
<td class="bc-supports-no"> No</td>
<td class="bc-supports-no"> No</td>
<td class="bc-supports-no">1 — 59</td>
<td class="bc-supports-no"> No</td>
<td class="bc-supports-no"> No</td>
<td class="bc-supports-no"> No</td>
</tr>
<tr>
<th scope="row">Optional catch binding</th>
<td class="bc-supports-yes"> 66</td>
<td class="bc-supports-no"> No</td>
<td class="bc-supports-yes"> 58</td>
<td class="bc-supports-no"> No</td>
<td class="bc-supports-yes"> 53</td>
<td class="bc-supports-no"> No</td>
</tr>
</tbody>
</table>
<table class="bc-table bc-table-js">
<thead>
<tr class="bc-platforms">
<th></th>
<th colspan="7">Mobile</th>
</tr>
<tr class="bc-browsers">
<th></th>
<th>Android webview</th>
<th>Chrome for Android</th>
<th>Edge Mobile</th>
<th>Firefox for Android</th>
<th>Opera for Android</th>
<th>iOS Safari</th>
<th>Samsung Internet</th>
</tr>
</thead>
<tbody>
<tr>
<th scope="row">Basic support</th>
<td class="bc-supports-yes"> Yes</td>
<td class="bc-supports-yes"> Yes</td>
<td class="bc-supports-yes"> Yes</td>
<td class="bc-supports-yes"> 4</td>
<td class="bc-supports-yes"> Yes</td>
<td class="bc-supports-yes"> Yes</td>
<td class="bc-supports-yes"> Yes</td>
</tr>
<tr>
<th scope="row">Conditional clauses 
</th>
<td class="bc-supports-no"> No</td>
<td class="bc-supports-no"> No</td>
<td class="bc-supports-no"> No</td>
<td class="bc-supports-no">4 — 59</td>
<td class="bc-supports-no"> No</td>
<td class="bc-supports-no"> No</td>
<td class="bc-supports-no"> No</td>
</tr>
<tr>
<th scope="row">Optional catch binding</th>
<td class="bc-supports-yes"> 66</td>
<td class="bc-supports-yes"> 66</td>
<td class="bc-supports-no"> No</td>
<td class="bc-supports-yes"> 58</td>
<td class="bc-supports-yes"> 53</td>
<td class="bc-supports-no"> No</td>
<td class="bc-supports-no"> No</td>
</tr>
</tbody>
</table>
<table class="bc-table bc-table-js">
<thead>
<tr class="bc-platforms">
<th></th>
<th colspan="1">Server</th>
</tr>
<tr class="bc-browsers">
<th></th>
<th>Node.js</th>
</tr>
</thead>
<tbody>
<tr>
<th scope="row">Basic support</th>
<td class="bc-supports-yes"> Yes</td>
</tr>
<tr>
<th scope="row">Conditional clauses 
</th>
<td class="bc-supports-no"> No</td>
</tr>
<tr>
<th scope="row">Optional catch binding</th>
<td class="bc-supports-no"> No</td>
</tr>
</tbody>
</table>
</div> <h2 id="See_also">See also</h2> <ul> <li><a href="../global_objects/error"><code>Error</code></a></li> <li><a href="throw"><code>throw</code></a></li> </ul><div class="_attribution">
  <p class="_attribution-p">
    <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch$edit" class="_attribution-link">Edit this page on MDN</a>
  </p>
</div>
<div class="_attribution">
  <p class="_attribution-p">
    &copy; 2005&ndash;2018 Mozilla Developer Network and individual contributors.<br>Licensed under the Creative Commons Attribution-ShareAlike License v2.5 or later.<br>
    <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch" class="_attribution-link">https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch</a>
  </p>
</div>
